- name: Get information about the cluster
  set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"
- name: Determine the cluster type
  set_fact:
    is_openshift: "{{ True if 'route.openshift.io' in api_groups else False }}"
    is_k8s: "{{ False if 'route.openshift.io' in api_groups else True }}"
    is_minikube: "{{ True if lookup('env', 'MOLECULE_CLUSTER_TYPE') == 'minikube' else False }}"
    is_kind: "{{ True if lookup('env', 'MOLECULE_CLUSTER_TYPE') == 'kind' else False }}"
- name: Determine the Istio implementation
  set_fact:
    is_maistra: "{{ True if 'maistra.io' in api_groups else False }}"

- name: Get Kiali CR if present
  set_fact:
    kiali_cr: "{{ lookup('k8s', api_version='kiali.io/v1alpha1', kind='Kiali', namespace=cr_namespace, resource_name=custom_resource.metadata.name) }}"

- name: Get Kiali Operator Pod
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ kiali.operator_namespace }}"
    label_selectors:
    - app = kiali-operator
  register: kiali_operator_pod

- name: Get Kiali Pod
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ kiali.install_namespace }}"
    label_selectors:
    - app = kiali
  register: kiali_pod

- name: Get Kiali Configmap
  set_fact:
    kiali_configmap: "{{ lookup('k8s', api_version='v1', kind='ConfigMap', namespace=kiali.install_namespace, resource_name='kiali') }}"

- name: Format Configmap
  set_fact:
    kiali_configmap: "{{ kiali_configmap.data['config.yaml'] | from_yaml }}"

- name: Get Kiali Deployment
  k8s_info:
    api_version: apps/v1
    kind: Deployment
    namespace: "{{ kiali.install_namespace }}"
    label_selectors:
    - app = kiali
  register: kiali_deployment

- name: Get Kiali Service
  k8s_info:
    api_version: v1
    kind: Service
    namespace: "{{ kiali.install_namespace }}"
    label_selectors:
    - app = kiali
  register: kiali_service

- name: Get Kiali Route
  k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    namespace: "{{ kiali.install_namespace }}"
    label_selectors:
    - app = kiali
  register: kiali_route
  when:
  - is_openshift == True

- name: Determine the Kiali Route URL on OpenShift
  set_fact:
    kiali_base_url: "https://{{ kiali_route.resources[0].spec.host }}"
  when:
  - is_openshift == True

- name: Determine the Kiali Ingress URL on minikube
  set_fact:
    kiali_base_url: "https://{{ lookup('env', 'MOLECULE_MINIKUBE_IP') }}/kiali"
  when:
  - is_minikube == True

- name: Determine the Kiali Ingress URL on kind
  set_fact:
    kiali_base_url: "https://{{ kiali_service.resources[0].status.loadBalancer.ingress[0].ip }}/kiali"
  when:
  - is_kind == True
