name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build operator
        run: make build
      - name: Install operator-sdk
        run: make .ensure-operator-sdk-exists
      - name: Validate OSSM metadata
        run: |
          _output/operator-sdk-install/operator-sdk version
          cat manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml | KIALI_OPERATOR_VERSION="2.0.0" KIALI_OLD_OPERATOR_VERSION="1.0.0" KIALI_OPERATOR_TAG=":2.0.0" KIALI_1_24_TAG=":1.24.0" KIALI_1_12_TAG=":1.12.0" KIALI_1_0_TAG=":1.0.0" CREATED_AT="2021-01-01T00:00:00Z" envsubst > manifests/kiali-ossm/manifests/csv.yaml ; mv manifests/kiali-ossm/manifests/csv.yaml manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml
          _output/operator-sdk-install/operator-sdk bundle validate --verbose manifests/kiali-ossm
      # The new SDK can not validate the old format which we still use right now
      #- name: Validate community metadata
      #  run: |
      #    # _output/operator-sdk-install/operator-sdk bundle validate --verbose manifests/kiali-community
      #    # _output/operator-sdk-install/operator-sdk bundle validate --verbose manifests/kiali-upstream
